[character]
# success_symbol = "[â¯](bold white)"
# error_symbol = "[â¯](bold white)"

[nodejs]
symbol = "ğŸŒ± "

[git_status]
style = "bold purple"

[git_branch]
format = "on [$symbol$branch($remote_name)]($style) "
